[tool.poetry]
name = "hypermodern-python"
version = "0.1.0"
description = "A template package based on The Hypermodern Project"
authors = ["Guy Hoozdis <GuyHoozdis@users.noreply.github.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/guyhoozdis/hypermodern-python"
repository = "https://github.com/guyhoozdis/hypermodern-python"
keywords = ["hypermodern", "template", "package"]


[tool.poetry.dependencies]
python = ">=3.8,<3.13"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
