name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.11
        architecture: x64
    - run: pip install nox==2024.4.15
    - run: pip install poetry==1.8.3
    - run: nox
